services: 
- type: web
  name: core
  env: python
  buildCommand: "./build.sh"        # ensure it's a string
  startCommand: cd DjangoCRM && python manage.py collectstatic --noinput && gunicorn core.wsgi:application
  repo: https://github.com/jonniuz1/DjangoCRM.git # optional
  # plan: standard # optional
  healthCheckPath: /
  # autoDeploy: false             # optional
